version: '3'
services:

  # MongoDB
  mongodb:
    image: mongo:5.0.15
    container_name: mongodb
    ports:
      - 127.0.0.1:27017:27017
    working_dir: /tmp
    volumes:
      - ./dummy_data:/tmp/dummy_data
      - ./schemas:/tmp/schemas
      - ./import.sh:/tmp/import.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Lightweight MongoDB admin interface
  # mongodb_express:
  #   image: mongo-express
  #   container_name: mongodb_express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   network_mode: "host"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy